### PR TITLE
Fix a typo

### PR DESCRIPTION
**Pull request by janklan**

### CODE REVIEW

**Comment by brunoprietog** [comment]
Previously fixed in #167

**Comment by janklan** [comment]
Huh did you refer a wrong PR?

**Comment by brunoprietog** [comment]
Oh yes sorry, my mistake, it was #163

**Comment by janklan** [comment]
Cool. Sorry, it was a bit confusing, so I thought I'd double check.

**Comment by brunoprietog** [comment]
No worries! Thank you for contributing. Contributions are always welcome 🙂

**Pull request closed without merging**
